apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-boot-backend
  namespace: myapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-boot-backend
  template:
    metadata:
      namespace: myapp
      labels:
        app: spring-boot-backend
    spec:
      containers:
        - name: spring-boot-backend
          image: thinh23/spring-boot-backend:kube
          ports:
            - containerPort: 8080


