apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql-statefulset
  namespace: myapp
spec:
  serviceName: mysqldb
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      namespace: myapp
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: mysql
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-pass
                  key: MYSQL_ROOT_PASSWORD
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: init-scripts
              mountPath: /docker-entrypoint-initdb.d
      volumes:
        - name: init-scripts
          configMap:
            name: mysql-initdb-config
        - name: mysql-storage
          persistentVolumeClaim:
            claimName: mysql-pvc

