apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-configuration
  namespace: ingress-nginx
data:
  use-proxy-protocol: "false"
  externalTrafficPolicy: Local
  proxy-real-ip-cidr: ""
  class: "nginx"
  publish-service: "my-ingress-nginx-controller"
  externalIPs: "192.168.0.100"
